import { type Types, type QueryFilter, type ClientSession, type FlattenMaps } from 'mongoose';
import { Book } from '../models/Book';
import type { IBook, BookStatus } from '../models/Book';
import type { CreateBookInput, UpdateBookInput } from '../utils/validationSchemas';
import type { PaginationParams, PaginatedResult } from '../utils/pagination';
import { buildPaginationMeta } from '../utils/pagination';

export interface BookFilters {
  search?: string;
  genre?: string;
  status?: BookStatus;
}

/**
 * BookRepository — pure DB access only.
 * No business logic, no HTTP, no validation.
 * isDeleted: false is ALWAYS applied here — never rely on callers to filter it.
 */
export class BookRepository {
  /**
   * Create a new book document.
   * embedding — pre-generated by BookService before calling here.
   */
  async create(
    data: CreateBookInput,
    createdBy: Types.ObjectId,
    embedding?: number[],
  ): Promise<IBook> {
    return Book.create({
      ...data,
      availableCopies: data.totalCopies,
      createdBy,
      updatedBy: createdBy,
      ...(embedding && { embedding }),
    });
  }

  /**
   * Find a single non-deleted book by its MongoDB _id.
   * Returns null if not found or soft-deleted.
   */
  async findById(id: string): Promise<IBook | null> {
    return Book.findOne({ _id: id, isDeleted: false });
  }

  /**
   * Find a single non-deleted book by ISBN.
   * Used for uniqueness checks in the service layer.
   */
  async findByIsbn(isbn: string): Promise<IBook | null> {
    return Book.findOne({ isbn, isDeleted: false });
  }

  /**
   * Paginated list with optional text search and field filters.
   * Always excludes soft-deleted documents.
   */
  async findWithFilters(
    filters: BookFilters,
    pagination: PaginationParams,
  ): Promise<PaginatedResult<IBook>> {
    const query: QueryFilter<IBook> = { isDeleted: false };

    // Full-text search on title / author / description (weighted text index)
    if (filters.search?.trim()) {
      query.$text = { $search: filters.search.trim() };
    }

    if (filters.genre) {
      query.genre = filters.genre;
    }

    if (filters.status) {
      query.status = filters.status;
    }

    const [items, totalItems] = await Promise.all([
      Book.find(query)
        .skip(pagination.skip)
        .limit(pagination.limit)
        .sort(filters.search ? { score: { $meta: 'textScore' } } : { createdAt: -1 }),
      Book.countDocuments(query),
    ]);

    return {
      items,
      pagination: buildPaginationMeta(pagination.page, pagination.limit, totalItems),
    };
  }

  /**
   * Partial update — only fields provided in data are changed.
   * Returns the updated document, or null if not found / soft-deleted.
   */
  async updateById(
    id: string,
    data: UpdateBookInput & { updatedBy: Types.ObjectId; embedding?: number[] },
  ): Promise<IBook | null> {
    return Book.findOneAndUpdate(
      { _id: id, isDeleted: false },
      { $set: data },
      { returnDocument: 'after', runValidators: true },
    );
  }

  /**
   * Soft delete — sets isDeleted + deletedAt, never removes the document.
   * Returns the updated document, or null if already deleted / not found.
   */
  async softDelete(id: string, deletedBy: Types.ObjectId): Promise<IBook | null> {
    return Book.findOneAndUpdate(
      { _id: id, isDeleted: false },
      { $set: { isDeleted: true, deletedAt: new Date(), updatedBy: deletedBy } },
      { returnDocument: 'after' },
    );
  }

  /**
   * Fetch ALL non-deleted books including their embedding vectors.
   * Used exclusively by BookService.semanticSearch — embedding is stripped
   * before the result leaves the service layer.
   *
   * .lean() returns plain JS objects (no Mongoose overhead, no .save()).
   * .select('+embedding') is required because the field is select:false.
   */
  async findAllWithEmbedding(): Promise<Array<FlattenMaps<IBook>>> {
    return Book.find({ isDeleted: false }).select('+embedding').lean<Array<FlattenMaps<IBook>>>();
  }

  // ── Transaction-aware copy-count helpers ─────────────────────────────────
  // Called ONLY from BorrowService inside a mongoose session/transaction.
  // Both methods use findOneAndUpdate with $inc for atomicity.

  /**
   * Decrement availableCopies by 1 inside a transaction.
   * Returns the updated book, or null if the book is not found / deleted.
   * Does NOT enforce business rules — the service must check before calling.
   */
  async decrementCopies(bookId: Types.ObjectId, session: ClientSession): Promise<IBook | null> {
    return Book.findOneAndUpdate(
      { _id: bookId, isDeleted: false },
      [
        {
          $set: {
            availableCopies: { $subtract: ['$availableCopies', 1] },
            // When copies hit 0, flip status to out_of_stock
            status: {
              $cond: {
                if: { $lte: [{ $subtract: ['$availableCopies', 1] }, 0] },
                then: 'out_of_stock',
                else: '$status',
              },
            },
          },
        },
      ],
      { returnDocument: 'after', session, updatePipeline: true },
    );
  }

  /**
   * Increment availableCopies by 1 inside a transaction.
   * Returns the updated book, or null if the book is not found / deleted.
   */
  async incrementCopies(bookId: Types.ObjectId, session: ClientSession): Promise<IBook | null> {
    return Book.findOneAndUpdate(
      { _id: bookId, isDeleted: false },
      [
        {
          $set: {
            availableCopies: { $add: ['$availableCopies', 1] },
            // When a copy is returned, re-open the book if it was out_of_stock
            status: {
              $cond: {
                if: { $eq: ['$status', 'out_of_stock'] },
                then: 'available',
                else: '$status',
              },
            },
          },
        },
      ],
      { returnDocument: 'after', session, updatePipeline: true },
    );
  }
}

// Singleton — one instance shared across the app
export const bookRepository = new BookRepository();
